### ISSUE TITLE
OIDC issue with KanIDM backend

### ISSUE THREAD

**Issue by stryan** [sissbruecker/linkding#1191]
I'm trying to move my Linkding install from using Authelia for auth to KanIDM. I've configured it like so:

```
LD_SERVER_PORT=9090
LD_ENABLE_OIDC=True
OIDC_OP_AUTHORIZATION_ENDPOINT=https://auth.example.com/ui/oauth2
OIDC_OP_TOKEN_ENDPOINT=https://auth.example.com/oauth2/token
OIDC_OP_USER_ENDPOINT=https://auth.example.com/oauth2/openid/linkding/userinfo
OIDC_OP_JWKS_ENDPOINT=https://auth.example.com/oauth2/openid/linkding/public_key.jwk
OIDC_USE_PKCE=True
OIDC_RP_SIGN_ALGO=ES256
OIDC_RP_CLIENT_ID=linkding
OIDC_RP_CLIENT_SECRET=<SECRET>
```
following the guidelines on https://kanidm.github.io/kanidm/stable/integrations/oauth2.html and https://mozilla-django-oidc.readthedocs.io/en/stable/ .

When I go to login it redirects to my KanIDM instance, then back to the Linkding login page.

I see the following in the Linkding logs:
```
Sep 24 20:21:33 kitezh linkding[10987]: [pid: 20|app: 0|req: 1/2] ::ffff:10.88.0.1 () {58 vars in 998 bytes} [Thu Sep 25 00:21:32 2025] GET / => generated 0 bytes in 1164 msecs (HTTP/1.1 302) 9 headers in 280 bytes (1 switches on core 0)
Sep 24 20:21:34 kitezh linkding[10987]: [pid: 22|app: 0|req: 2/3] ::ffff:10.88.0.1 () {58 vars in 1009 bytes} [Thu Sep 25 00:21:33 2025] GET /login/ => generated 6141 bytes in 444 msecs (HTTP/1.1 200) 11 headers in 509 bytes (1 switches on core 1)
Sep 24 20:21:35 kitezh linkding[10987]: [pid: 20|app: 0|req: 2/4] ::ffff:10.88.0.1 () {60 vars in 1090 bytes} [Thu Sep 25 00:21:35 2025] GET /oidc/authenticate/ => generated 0 bytes in 60 msecs (HTTP/1.1 302) 10 headers in 751 bytes (1 switches on core 1)
Sep 24 20:21:36 kitezh linkding[10987]: 2025-09-25 00:21:36,651 WARNING failed to get or create user: Claims verification failed
Sep 24 20:21:36 kitezh linkding[10987]: [pid: 22|app: 0|req: 3/5] ::ffff:10.88.0.1 () {58 vars in 2342 bytes} [Thu Sep 25 00:21:35 2025] GET /oidc/callback/?code=<BIGLONGCODE> => generated 0 bytes in 1126 msecs (HTTP/1.1 302) 9 headers in 266 bytes (1 switches on core 0)
Sep 24 20:21:36 kitezh linkding[10987]: [pid: 20|app: 0|req: 3/6] ::ffff:10.88.0.1 () {58 vars in 997 bytes} [Thu Sep 25 00:21:36 2025] GET / => generated 0 bytes in 9 msecs (HTTP/1.1 302) 9 headers in 280 bytes (1 switches on core 0)
Sep 24 20:21:36 kitezh linkding[10987]: [pid: 22|app: 0|req: 4/7] ::ffff:10.88.0.1 () {58 vars in 1009 bytes} [Thu Sep 25 00:21:36 2025] GET /login/ => generated 6141 bytes in 23 msecs (HTTP/1.1 200) 11 headers in 509 bytes (1 switches on core 1)
Sep 24 20:21:37 kitezh linkding[10987]: [pid: 22|app: 0|req: 5/8] ::ffff:10.88.0.1 () {30 vars in 473 bytes} [Thu Sep 25 00:21:37 2025] GET /health => generated 42 bytes in 6 msecs (HTTP/1.1 200) 8 headers in 251 bytes (1 switches on core 0)
```

and on the KanIDM side I can see this log line:

```
Sep 24 20:21:36 vraska kanidm[7117]: 35ebb1d0-89f8-4d15-ad5a-f493ed7e0a0d INFO     request [ 141µs | 57.46% / 100.00% ] method: GET | uri: /oauth2/openid/linkding/public_key.jwk | version: HTTP/1.1
Sep 24 20:21:36 vraska kanidm[7117]: 35ebb1d0-89f8-4d15-ad5a-f493ed7e0a0d INFO     ┝━ ｉ [info]:  | connection_addr: [::ffff:10.89.0.27]:59914 | client_ip_addr: ::ffff:10.89.0.27
Sep 24 20:21:36 vraska kanidm[7117]: 35ebb1d0-89f8-4d15-ad5a-f493ed7e0a0d INFO     ┕━ handle_oauth2_openid_publickey [ 59.9µs | 42.54% ]
Sep 24 20:21:36 vraska kanidm[7117]: 38177504-e796-4638-b725-e382fa4b3671 INFO     request [ 1.20ms | 18.35% / 100.00% ] method: GET | uri: /oauth2/openid/linkding/userinfo | version: HTTP/1.1
Sep 24 20:21:36 vraska kanidm[7117]: 38177504-e796-4638-b725-e382fa4b3671 INFO     ┝━ ｉ [info]:  | connection_addr: [::ffff:10.89.0.27]:59914 | client_ip_addr: ::ffff:10.89.0.27
Sep 24 20:21:36 vraska kanidm[7117]: 38177504-e796-4638-b725-e382fa4b3671 INFO     ┝━ pre_validate_client_auth_info [ 20.5µs | 0.67% / 1.71% ]
Sep 24 20:21:36 vraska kanidm[7117]: 38177504-e796-4638-b725-e382fa4b3671 INFO     │  ┕━ validate_client_auth_info_to_uat [ 12.5µs | 1.04% ]
Sep 24 20:21:36 vraska kanidm[7117]: 38177504-e796-4638-b725-e382fa4b3671 ERROR    │     ┝━ 🚨 [error]: JWS is signed by a key that is not present in this KeyObject
Sep 24 20:21:36 vraska kanidm[7117]: 38177504-e796-4638-b725-e382fa4b3671 INFO     │     ┕━ ｉ [info]: Unable to verify token | event_tag_id: 10 | err: KP0022KeyObjectJwsNotAssociated
Sep 24 20:21:36 vraska kanidm[7117]: 38177504-e796-4638-b725-e382fa4b3671 INFO     ┕━ handle_oauth2_openid_userinfo [ 960µs | 79.94% ]
Sep 24 20:21:36 vraska kanidm[7117]: 38177504-e796-4638-b725-e382fa4b3671 INFO        ┕━ ｉ [info]: A valid parent and oauth2 session value exists for this token | event_tag_id: 10
```

Which makes me think Linkding is doing something odd with the returned JWT. Any thoughts?

**Comment by yaleman** [comment]
* The default scopes don't include `openid` which is required per the Kanidm docs https://kanidm.github.io/kanidm/master/integrations/oauth2.html - so I'd suggest setting `OIDC_RP_SCOPES=openid email profile`
* The `JWS is signed by a key that is not present in this KeyObject` error should be fixed by https://github.com/kanidm/kanidm/pull/3865

**Comment by stryan** [comment]
Unfortunately the issue persists even with the fixed scopes: I tried both `OIDC_RP_SCOPES=openid email profile` and `OIDC_RP_SCOPES=oidc openid email profile` , as well as making sure the right scope map is set KanIDM side with
`kanidm system oauth2 update-scope-map linkding idm_all_persons openid email profile oidc` . Would I need to wait until that PR is part of a release?

**Comment by stryan** [comment]
KanIDM nightly fixed the error message on that end and I think the issue was the one account I was using to test login was the one account that didn't have an email attribute set in KanIDM. I've fixed that and can login now.

Not sure if it's possible for Linkding to provide a more specific error message since I know it's coming from django-oidc, but either way I'll close this and any relevant documentation updates can be made if found appropriate.
